window.SOUND_PAD = {
  ambients: [
    { id: "site-hum", label: "Site Hum" },
    { id: "truck-idle", label: "Truck Idle" },
    { id: "wind-blow", label: "Wind Blow" },
    { id: "generator", label: "Generator" },
    { id: "road-traffic", label: "Road Traffic" },
    { id: "rain-roof", label: "Rain Roof" },
    { id: "bass-pulse", label: "Bass Pulse" },
    { id: "crowd-loop", label: "Crowd Loop" },
    { id: "drone-rumble", label: "Drone Rumble" },
    { id: "heartbeat", label: "Heart Beat" },
  ],
  effects: [
    { id: "john-joy", label: "John & Joy!" },
    { id: "sand-gravel", label: "Sand Gravel" },
    { id: "best-quality", label: "Best Quality" },
    { id: "ready-travel", label: "Ready Travel" },
    { id: "truck-horn", label: "Truck Horn" },
    { id: "air-horn", label: "Air Horn" },
    { id: "boom-boom", label: "Boom Boom" },
    { id: "whoosh", label: "Whoosh" },
    { id: "crowd-hey", label: "Crowd Hey" },
    { id: "clap-stomp", label: "Clap Stomp" },
    { id: "engine-rev", label: "Engine Rev" },
    { id: "load-dump", label: "Load Dump" },
    { id: "siren", label: "Siren" },
    { id: "cash-ding", label: "Cash Ding" },
    { id: "gravel-pour", label: "Gravel Pour" },
    { id: "jackhammer", label: "Jackhammer" },
    { id: "zoom-zoom", label: "Zoom Zoom" },
    { id: "lets-go", label: "Let's Go!" },
    { id: "woah-oh", label: "Woah Oh" },
    { id: "build-it", label: "Build It!" },
    { id: "order-now", label: "Order Now!" },
    { id: "tara-na", label: "Tara Na!" },
    { id: "number-one", label: "Number One!" },
    { id: "digidi-hey", label: "Digidi Hey" },
    { id: "gravel-hook", label: "Gravel Hook" },
    { id: "fast-delivery", label: "Fast Delivery" },
    { id: "strong-foundation", label: "Strong Base" },
    { id: "everybody-noise", label: "Make Noise" },
    { id: "load-it-up", label: "Load It Up" },
    { id: "drive-away", label: "Drive Away" },
    { id: "winning-race", label: "Winning Race" },
    { id: "call-us-now", label: "Call Us Now" },
    { id: "truck-ready", label: "Truck Ready" },
    { id: "glass-break", label: "Glass Break" },
    { id: "explosion", label: "Explosion" },
    { id: "record-scratch", label: "Record Scratch" },
    { id: "laser-zap", label: "Laser Zap" },
    { id: "party-horn", label: "Party Horn" },
    { id: "bye-bye", label: "Bye Bye!" },
  ],
};
